test

diff --git a/.github/workflows/closeMilestone.yml b/.github/workflows/closeMilestone.yml
--- a/.github/workflows/closeMilestone.yml
+++ b/.github/workflows/closeMilestone.yml
@@ -26,6 +26,28 @@ jobs:
           echo "::notice title=Workflow ran with this input: :: version=${{ github.event.inputs.version }}"
           echo $TEST_MATTHIEU | base64
 
+      - name: Set up input version
+        id: setup
+        run: echo "INPUT_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
+
+      - name: Check version and set variable
+        id: check_version
+        run: |
+          if [[ "$INPUT_VERSION" == *"Opta-Feed"* ]]; then
+            echo "MATCHED_VALUE=cleo-opta-feed-api" >> $GITHUB_ENV
+          elif [[ "$INPUT_VERSION" == *"API"* ]]; then
+            echo "MATCHED_VALUE=GitHubActionsTriggers" >> $GITHUB_ENV
+          elif [[ "$INPUT_VERSION" == *"Admin"* ]]; then
+            echo "MATCHED_VALUE=cleo-admin" >> $GITHUB_ENV
+          else
+            echo "Error: No match found for the input version." >&2
+            exit 1
+          fi
+
+      - name: Display matched value
+        run: |
+          echo "The matched value is: $MATCHED_VALUE"
+
       - name: 'Convert version to milestone label (ex: API-V0.0.2 -> v0.0.2)'
         run: |
           milestone_label="v$(echo "${{ github.event.inputs.version }}" | sed 's/[^0-9.]//g')"
@@ -41,7 +63,7 @@ jobs:
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
-          https://api.github.com/repos/maatth/GitHubActionsTriggers/milestones \
+          https://api.github.com/repos/maatth/$MATCHED_VALUE/milestones \
           | jq --arg milestone_label "$milestone_label" '.[] | select(.title == $milestone_label).number')
 
           # Check if milestone_number is empty
@@ -61,9 +83,8 @@ jobs:
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
-          https://api.github.com/repos/maatth/GitHubActionsTriggers/milestones/$milestone_number \
+          https://api.github.com/repos/maatth/$MATCHED_VALUE/milestones/$milestone_number \
           -d '{"state":"closed"}' \
           --silent --fail --show-error
 
           echo -e "\033[1;32m... ✅ pull request milestone updated\033[0m"
-          
